# This is a basic workflow to help you get started with boman.ai

name: Bomanai marekteplan test
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Boman-scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a single command using the runners shell
      - name: boman-ai-action
        uses: i4mmaddy/boman-ai-action@v7
        with:
          action: 'run' # or test-saas, test-yaml
          #failbuild: 'high' #optional # or 'high' or 'medium or 'low'
          #zap_session_script: 'path/to/your/zap_session_script' #optional
          config: './boman_qa.yaml' #optional
          use-sudo: 'true' #default is true
          boman_saas_url: 'https://qa.boman.ai'
            
